### ISSUE TITLE
Library won't compile, grcp error

### ISSUE THREAD

**Issue by 0plus1** [sajari/sdk-node#28]
I have debugged the issue quite in depth and it's definitely related to this library.
I tried changing node version (12 and 15) and the error persists, it starts with a warning:

```warning @sajari/sdk-node > grpc > node-pre-gyp@0.10.3: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future```

And ends with an error: 

```
2 errors generated.
make: *** [Release/obj.target/grpc_node/ext/call.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/Users/xxx/sajari/node_modules/grpc/src/node/extension_binary/node-v88-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/xxx/sajari/node_modules/grpc/src/node/extension_binary/node-v88-darwin-x64-unknown" "--napi_version=8" "--node_abi_napi=napi"
gyp ERR! cwd /Users/xxx/sajari/node_modules/grpc
gyp ERR! node -v v15.12.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/xxx/sajari/node_modules/grpc/src/node/extension_binary/node-v88-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/xxx/sajari/node_modules/grpc/src/node/extension_binary/node-v88-darwin-x64-unknown --napi_version=8 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/xxx/sajari/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
node-pre-gyp ERR! System Darwin 19.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/xxx/sajari/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /Users/xxx/sajari/node_modules/grpc
node-pre-gyp ERR! node -v v15.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/xxx/sajari/node_modules/grpc/src/node/extension_binary/node-v88-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/xxx/sajari/node_modules/grpc/src/node/extension_binary/node-v88-darwin-x64-unknown --napi_version=8 --node_abi_napi=napi' (1)
```

**Comment by jonathaningram** [comment]
Hi @0plus1 sorry that you're having issues! What version of the package are you using?

We have published a v4 series that doesn't use gRPC anymore, now that our v4 API is just an OpenAPI REST API.

Can you please try version `@sajari/sdk-node@4.0.0-alpha.12`?

**Comment by 0plus1** [comment]
Hi @jonathaningram 4.0.0 does indeed works! Thank you so much for your super-prompt response.
